// Builds the Word Guess word lists from open sources:
//   word-list (MIT)                   -> every valid 5-letter guess
//   subtlex-word-frequencies (ISC)    -> how common a word is, so answers are words people know
//   profane-words (WTFPL)             -> never chosen as an answer
// Output is written to the web app (guesses + practice answers) and the API (same files, embedded).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const dictionary = new Set(
  readFileSync(new URL('./node_modules/word-list/words.txt', import.meta.url), 'utf8').split('\n').map((w) => w.trim()),
);
const frequencies = require('subtlex-word-frequencies');
const profane = new Set(require('profane-words').map((w) => w.toLowerCase()));

const isFive = (w) => /^[a-z]{5}$/.test(w);

const guesses = [...dictionary].filter(isFive).sort();

const looksInflected = (w) => {
  const has = (x) => dictionary.has(x);
  if (w.endsWith('ies') && has(w.slice(0, -3) + 'y')) return true; // cries, dries
  if (w.endsWith('ves') && (has(w.slice(0, -3) + 'f') || has(w.slice(0, -3) + 'fe'))) return true; // elves
  if (w.endsWith('es') && (has(w.slice(0, -2)) || has(w.slice(0, -1)))) return true; // ashes, boxes, buses
  if (w.endsWith('s') && !w.endsWith('ss') && !w.endsWith('us') && !w.endsWith('is') && has(w.slice(0, -1))) return true;
  if (w.endsWith('ed') && (has(w.slice(0, -1)) || has(w.slice(0, -2)))) return true; // past tense
  if (w.endsWith('ing') && (has(w.slice(0, -3)) || has(w.slice(0, -3) + 'e'))) return true; // suing, dying
  return false;
};

// Hand-picked removals: slang, brand names and words too obscure for a daily puzzle. Edit exclude.txt to curate.
const excluded = new Set(readFileSync(new URL('./exclude.txt', import.meta.url), 'utf8').split('\n').filter(Boolean));
const ANSWER_COUNT = 1800;
const answers = frequencies
  .map(({ word, count }) => ({ word: word.toLowerCase(), count, name: /^[A-Z]/.test(word) }))
  // Entries that only exist capitalised are mostly first names; keep them only when very common.
  .filter(({ name, count }) => !name || count >= 3000)
  .filter(({ word }) => isFive(word) && dictionary.has(word) && !profane.has(word) && !excluded.has(word) && !looksInflected(word))
  .reduce((acc, { word, count }) => (acc.has(word) ? acc : acc.set(word, count)), new Map());

const topAnswers = [...answers.entries()]
  .sort((a, b) => b[1] - a[1])
  .slice(0, ANSWER_COUNT)
  .map(([word]) => word)
  .sort();

const allGuesses = guesses;

console.log(`valid guesses: ${allGuesses.length}, answers: ${topAnswers.length}`);

// The alphabetical answer pool is public (it ships in the app for practice play). The daily order is NOT:
// schedule.mjs orders it with a secret seed.
writeFileSync(new URL('./answers.txt', import.meta.url), topAnswers.join('\n') + '\n');

const webDir = new URL('../../../apps/web/src/app/games/word-guess/data/', import.meta.url);
mkdirSync(webDir, { recursive: true });
const asModule = (name, words, doc) =>
  `/* Generated by tools/generators/words/build.mjs. Do not edit. */\n/** ${doc} */\nexport const ${name}: string = '${words.join('\\n')}';\n`;
writeFileSync(new URL('guesses.ts', webDir), asModule('GUESSES', allGuesses, 'Every word accepted as a guess.'));
writeFileSync(new URL('answers.ts', webDir), asModule('ANSWERS', topAnswers, 'Words used for practice play, alphabetical.'));

const apiDir = new URL('../../../apps/api/Zenigma.Api/Games/WordGuess/', import.meta.url);
mkdirSync(apiDir, { recursive: true });
writeFileSync(new URL('guesses.txt', apiDir), allGuesses.join('\n') + '\n');
