namespace Zenigma.Api.Games.WordGuess;

/// <summary>Every word accepted as a guess, embedded in the assembly (generated by tools/generators/words).</summary>
public sealed class WordList
{
    private readonly HashSet<string> _valid;

    public WordList()
    {
        using var stream = typeof(WordList).Assembly.GetManifestResourceStream("guesses.txt")
            ?? throw new InvalidOperationException("guesses.txt is not embedded.");
        using var reader = new StreamReader(stream);
        _valid = reader.ReadToEnd()
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToHashSet(StringComparer.Ordinal);
    }

    public int Count => _valid.Count;

    public bool IsValid(string word) => _valid.Contains(word);
}
